### ISSUE TITLE
能反代多个emby服务器吗

### ISSUE THREAD

**Issue by s7ooL** [aquasofts/emby#1]
多个域名反代多个emby

**Comment by aquasofts** [comment]
抱歉，有点忙，才看到这条issue
未来会考虑添加此功能

这是一个暂时的解决办法
进入“/etc/nginx/sites-available”中将文件名称中带有“emby”或者带有"http"的文件修改一下名称
然后进入"/etc/nginx/sites-enabled"将同名文件删除
随后运行（需要修改一些东西）
"sudo ln -s /etc/nginx/sites-available/你修改后的文件名称 /etc/nginx/sites-enabled/"

**Comment by aquasofts** [comment]
> 抱歉，有点忙，才看到这条issue 未来会考虑添加此功能
> 
> 这是一个暂时的解决办法 进入“/etc/nginx/sites-available”中将文件名称中带有“emby”或者带有"http"的文件修改一下名称 然后进入"/etc/nginx/sites-enabled"将同名文件删除 随后运行（需要修改一些东西） "sudo ln -s /etc/nginx/sites-available/你修改后的文件名称 /etc/nginx/sites-enabled/"

这样你就可以重新运行脚本了

**Comment by s7ooL** [comment]
好的。感谢回复
